config/routes.rb
BandSite::Application.routes.draw do

  resources :users

  root :to => 'pages#home'

  match '/search', to: 'pages#search'

  match '/signup', to: 'users#new'



end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = user.email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness:{ case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else 
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper


  # Returns the Gravatar
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.slim
Doctype html
html
  head
    title 
      = yield(:title)
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  header.navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "band site",root_path, id: "logo"
          nav
            ul.nav.pull-right
              li = link_to "Home", root_path
              li = link_to "Search", search_path
              li = link_to "Sign in", '#'
  body
    .container
      ==yield
      footer.footer
        small This is a Footer, it will hold copyright things
      == debug(params) if Rails.env.development?

  

app/views/pages/home.html.slim
.center.hero-unit
  h1 Welcome to the Band Site

  p Find muscians to complete your band or find a band that fits your style. Its free and always will be

  =link_to "Sign up now!", new_user_path, class: "btn btn-large btn-primary"

  

app/views/pages/search.html.slim
h1 Pages#search
p Find me in app/views/pages/search.html.erb

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation 
    .alert.alert-error
      p The form contains #{pluralize(@user.errors.count, "error")}
    ul 
      - @user.errors.full_messages.each do |msg|
        li = (msg)

app/views/users/new.html.slim
= provide(:title, 'Sign up')
h1 Sign up
= render "shared/error_messages"
.row
  .span6.offset3
    = form_for(@user) do |f|
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.slim
= provide(:title, @user.name)
.row 
  aside.span4
    section
      h1
        = gravatar_for @user
        = @user.name